# parameters = dict(
#     batch=[64, 128],
#     lr=[3e-4, 1e-4],
#     wd=[1e-4],
#     lr_decay=[0.98],
#     mixup_a=[0.2],
#     mixup_p=[0.8],
#     use_augm_datasets=[True],
#     shift=[True],
#     sigma=[0.2],
#     weighted_sampler=[True],
#     class_weight=[1],
#     bag_size=[8],
#     n_MIL_Neurons=[64],
#     time_steps=[112],
#     lr_in=[None],
#     dropout_p=[0.15],
#     focal_loss=[0, 0.5, 1.0, 1.5],
#     exclude_outliers=[0, 1, 2],
#     min_quality=["train:1-val:2"]
# )
# DATASET_NAME = "logmel_combined_breaths_NEW_92msHop_184msFFT_fmax11000_224logmel"
# RUN_COMMENT = f"focal_loss_test"
# n_epochs = 250
# n_cross_validation_runs = 1
# USE_MIL = False
# MODEL_NAME = "resnet18"
#
# USE_TRAIN_VAL_TEST_SPLIT = True  # use a 70/15/15 split instead of an 80/20 split without test set
# QUICK_TRAIN_FOR_TESTS = False
# SAMPLES_PER_EPOCH = 1024
